# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.7.1'
  displayName: 'Install Node'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run test
  displayName: 'Run unit tests'

- script: |
    cd android
    bundle install
    fastlane build
  displayName: 'Build Android'