# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: 2.8$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '9.7.1'
#   displayName: 'Install Node'

# - script: npm install
#   displayName: 'Install dependencies'

# - script: npm run test
#   displayName: 'Run unit tests'

- task: VersionAssemblies@2
  inputs:
    sourcePath: 'android/app/'
    filePattern: 'build.gradle'
    versionSource: 'buildNumber'
    versionFormat: 'custom'
    customBuildRegex: '(?:\d.\d.\d+)'
    replaceVersionFormat: 'custom'
    customReplaceRegex: 'versionName "\d.\d.\d+'
    replacePrefix: 'versionName "'
  displayName: 'Android bump'
  
- script: cat android/app/build.gradle
  displayName: 'Android Build Cat'

- task: VersionAssemblies@2
  inputs:
    sourcePath: 'ios/azuredevopsbuild.xcodeproj/'
    filePattern: 'project.pbxproj'
    versionSource: 'buildNumber'
    versionFormat: 'custom'
    customBuildRegex: '(?:\d.\d.\d+)'
    replaceVersionFormat: 'custom'
    customReplaceRegex: 'MARKETING_VERSION = \d.\d.\d+'
    replacePrefix: 'MARKETING_VERSION ='
  displayName: 'iOS bump'

- script: cat ios/azuredevopsbuild.xcodeproj/project.pbxproj
  displayName: 'iOS Build Cat'